# Site settings
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 'tfire.io'
description: 'music, computers, musical computers.'
email: 'tyler@tfire.io'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tfire.github.io" # the base hostname & protocol for your site, e.g. http://example.com

header_pages:
   - index.md
   - about.md

# Build settings
# https://github.com/b2a3e8/jekyll-theme-console/tree/gh-pages
remote_theme: b2a3e8/jekyll-theme-console
#theme: jekyll-theme-console
markdown: kramdown
#style: dark
listen_for_clients_preferred_style: true
google_analytics: UA-74494101-2

plugins:
   - jekyll-seo-tag
#  - jekyll-feed
